// export const ADD_CART_DATA_START = "ADD_CART_DATA_START";
export const ADD_CART_DATA_SUCCESS = "ADD_CART_DATA_SUCCESS";
// export const ADD_CART_DATA_FAILED = "ADD_CART_DATA_FAILED";

export const DELETE_ITEM_FROM_CART = "DELETE_ITEM_FROM_CART";
export const INCREASE_QUANTITY = "INCREASE_QUANTITY";
export const DECREASE_QUANTITY = "DECREASE_QUANTITY";