export const GET_PRODUCT_PROFILE_START = "GET_PRODUCT_PROFILE_START";
export const GET_PRODUCT_PROFILE_SUCCESS = "GET_PRODUCT_PROFILE_SUCCESS";
export const GET_PRODUCT_PROFILE_FAILED = "GET_PRODUCT_PROFILE_FAILED";
