export const GET_PRODUCT_PROFILE_START = "GET_PRODUCT_PROFILE_START";
export const GET_PRODUCT_PROFILE_SUCCESS = "GET_PRODUCT_PROFILE_SUCCESS";
export const GET_PRODUCT_PROFILE_FAILED = "GET_PRODUCT_PROFILE_FAILED";
export const POST_REVIEW_START = "POST_REVIEW_START";
export const POST_REVIEW_SUCCESS = "POST_REVIEW_SUCCESS";
export const POST_REVIEW_FAILED = "POST_REVIEW_FAILED";
