export const GET_PRODUCTS_START = "GET_PRODUCTS_START";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAILED = "GET_PRODUCTS_FAILED";

export const GET_TOP_PRODUCTS_START= "GET_TOP_PRODUCTS_START"
export const GET_TOP_PRODUCTS_SUCCESS= "GET_TOP_PRODUCTS_SUCCESS"
export const GET_TOP_PRODUCTS_FAILED= "GET_TOP_PRODUCTS_FAILED"

export const GET_SEARCH_START = "GET_SEARCH_START";
export const GET_SEARCH_SUCCESS = "GET_SEARCH_SUCCESS";
export const GET_SEARCH_FAILED = "GET_SEARCH_FAILED";
