export const POST_ORDER_START = "POST_ORDER_START";
export const POST_ORDER_SUCCESS = "POST_ORDER_SUCCESS";
export const POST_ORDER_FAILED = "POST_ORDER_FAILED";

export const GET_MY_ORDERS_START = "GET_MY_ORDERS_START";
export const GET_MY_ORDERS_SUCCESS = "GET_MY_ORDERS_SUCCESS";
export const GET_MY_ORDERS_FAILED = "GET_MY_ORDERS_FAILED";

export const GET_ORDER_DETAILS_START = "GET_ORDER_DETAILS_START";
export const GET_ORDER_DETAILS_SUCCESS = "GET_ORDER_DETAILS_SUCCESS";
export const GET_ORDER_DETAILS_FAILED = "GET_ORDER_DETAILS_FAILED";