export const POST_SIGNUP_START = "POST_SIGNUP_START";
export const POST_SIGNUP_SUCCESS = "POST_SIGNUP_SUCCESS";
export const POST_SIGNUP_FAILED = "POST_SIGNUP_FAILED";

export const POST_LOGIN_START = "POST_LOGIN_START";
export const POST_LOGIN_SUCCESS = "POST_LOGIN_SUCCESS";
export const POST_LOGIN_FAILED = "POST_LOGIN_FAILED";

export const ADD_CART_DATA_START = "ADD_CART_DATA_START";
export const ADD_CART_DATA_SUCCESS = "ADD_CART_DATA_SUCCESS";
export const ADD_CART_DATA_FAILED = "ADD_CART_DATA_FAILED";